services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html:ro
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl:ro
      - ./ssl/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - nginx-network
      - opencode-serve

networks:
  nginx-network:
    driver: bridge
  opencode-serve:
    external: true
    name: opencode-serve_default
